#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Feb 03 16:55:22 CET 2022
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 2b887c7fb75644b8b68b7702e78de066 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot test_pulse_gen_behav xil_defaultlib.test_pulse_gen -log elaborate.log"
xelab -wto 2b887c7fb75644b8b68b7702e78de066 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot test_pulse_gen_behav xil_defaultlib.test_pulse_gen -log elaborate.log

