webtalk_init -webtalk_dir /home/dld2321a/Documents/VHDL/TP1_PulseGen/zybo-tp1/zybo-tp1.sim/sim_1/behav/xsim/xsim.dir/test_pulse_gen_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 10 17:28:22 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174350318_207303614_210750547_706" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b953f3f8-dacc-4fc1-9381-53047ded9f0d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2b887c7fb75644b8b68b7702e78de066" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Debian" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Debian GNU/Linux 11 (bullseye)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1125.124 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "69 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.07_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "117436_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1515080757 -regid "174350318_207303614_210750547_706" -xml /home/dld2321a/Documents/VHDL/TP1_PulseGen/zybo-tp1/zybo-tp1.sim/sim_1/behav/xsim/xsim.dir/test_pulse_gen_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/dld2321a/Documents/VHDL/TP1_PulseGen/zybo-tp1/zybo-tp1.sim/sim_1/behav/xsim/xsim.dir/test_pulse_gen_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/dld2321a/Documents/VHDL/TP1_PulseGen/zybo-tp1/zybo-tp1.sim/sim_1/behav/xsim/xsim.dir/test_pulse_gen_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
